"""Model Performance — AI analytics dashboard."""

import os

import streamlit as st

import stitch_shared as shared

shared.render_topbar("Model Performance", "Validation metrics · ROC · confusion matrix · training curves")
shared.render_kpi_strip()

st.markdown('<div class="page-wrap">', unsafe_allow_html=True)
st.markdown(
    '<p class="section-title">📈 Model Performance Analytics</p>'
    '<p class="section-sub">Production EfficientNetB3 evaluated on 4,000 held-out dermoscopy images.</p>',
    unsafe_allow_html=True,
)

metrics = shared.get_metrics()
mcols = st.columns(6)
for col, (label, key, is_pct) in zip(
    mcols,
    [
        ("Accuracy", "accuracy", True),
        ("AUC-ROC", "auc_roc", False),
        ("Sensitivity", "sensitivity", True),
        ("Specificity", "specificity", True),
        ("Precision", "precision", True),
        ("F1", "f1_score", False),
    ],
):
    val = metrics.get(key, shared.DEFAULT_METRICS.get(key))
    display = shared.fmt_pct(val) if is_pct else f"{float(val):.4f}"
    col.markdown(
        f"<div class='kpi-card'><div class='kpi-label'>{label}</div>"
        f"<div class='kpi-value' style='font-size:1.25rem'>{display}</div></div>",
        unsafe_allow_html=True,
    )

shared.render_v1_v2_comparison()
shared.render_metric_explainers()

st.markdown("---")
st.markdown('<p class="section-title">Evaluation Charts</p>', unsafe_allow_html=True)
st.markdown(
    '<p class="section-sub">Generated by evaluate_model.py on the frozen production checkpoint.</p>',
    unsafe_allow_html=True,
)

charts = [
    ("ROC Curve", "roc_curve.png", "Discrimination across thresholds — AUC 0.977"),
    ("Confusion Matrix", "confusion_matrix.png", "True vs predicted labels on test set"),
    ("Training Curves", "training_curves.png", "Two-phase focal-loss training convergence"),
]

for i in range(0, len(charts), 2):
    cols = st.columns(2)
    for col, (title, fname, caption) in zip(cols, charts[i : i + 2]):
        path = os.path.join("outputs", fname)
        with col:
            st.markdown(f'<div class="chart-frame"><strong>{title}</strong>', unsafe_allow_html=True)
            st.caption(caption)
            if os.path.exists(path):
                st.image(path, use_container_width=True)
            else:
                st.warning(f"Missing: outputs/{fname}")
            st.markdown("</div>", unsafe_allow_html=True)

cm = metrics.get("confusion_matrix")
if cm:
    st.markdown('<div class="ml-card" style="margin-top:16px">', unsafe_allow_html=True)
    st.markdown("**Test-set confusion matrix (counts)**")
    tn, fp = cm[0][0], cm[0][1]
    fn, tp = cm[1][0], cm[1][1]
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("True Negatives", f"{tn:,}", help="Benign correctly cleared")
    c2.metric("False Positives", f"{fp:,}", help="Benign flagged malignant")
    c3.metric("False Negatives", f"{fn:,}", help="Malignant missed")
    c4.metric("True Positives", f"{tp:,}", help="Malignant correctly detected")
    st.markdown("</div>", unsafe_allow_html=True)

shared.render_footer()
st.markdown("</div>", unsafe_allow_html=True)
